services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wordcounter
    ports:
      - "5600:5600"
    volumes:
      - ./data:/var/lib/postgresql/data
